# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Skivvy_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# import Skivvy as skivvy


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -120, 1231, 711))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.background.setObjectName("background")
        self.listen = QtWidgets.QLabel(self.centralwidget)
        self.listen.setGeometry(QtCore.QRect(350, 100, 311, 211))
        self.listen.setText("")
        self.listen.setPixmap(QtGui.QPixmap("Siri.gif"))
        self.listen.setScaledContents(True)
        self.listen.setObjectName("listen")
        self.load = QtWidgets.QLabel(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(0, 330, 981, 161))
        self.load.setText("")
        self.load.setPixmap(QtGui.QPixmap("loading_1.gif"))
        self.load.setScaledContents(True)
        self.load.setObjectName("load")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(200, 440, 121, 51))
        self.start.setStyleSheet("background-color: rgb(0, 0, 236);\n"
                                 "font: 75 24pt \"MS Shell Dlg 2\";\n"
                                 "color: rgb(255, 255, 255);")
        self.start.setObjectName("start")
        self.start.clicked.connect(self.start_clicked)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(650, 440, 121, 51))
        self.exit.setStyleSheet("background-color: rgb(0, 0, 236);\n"
                                "font: 75 24pt \"MS Shell Dlg 2\";\n"
                                "color: rgb(255, 255, 255);")
        self.exit.setObjectName("exit")
        self.exit.clicked.connect(self.exit_clicked)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(850, 10, 131, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 191, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("s2.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "START"))
        self.exit.setText(_translate("MainWindow", "EXIT"))

    def start_clicked(self):
        print("Start clicked")
        # call your logic here like skivvy.commands()

    def exit_clicked(self):
        print("Exit clicked")
        # this will end the program
        exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    # call intro here
    sys.exit(app.exec_())
